# Form implementation generated from reading ui file 'ui_mainmenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ui_mainwindow import Ui_MainWindow
from ui_theorydialog import Ui_TheoryDialog
from mainWindow import MainWindow

class Ui_MainMenu(QtWidgets.QWidget):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(260, 259)
        MainMenu.setStyleSheet("text-align: center;")
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_create = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create.setGeometry(QtCore.QRect(45, 190, 170, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_create.setFont(font)
        self.btn_create.setObjectName("btn_create")
        self.btn_theory = QtWidgets.QPushButton(self.centralwidget)
        self.btn_theory.setGeometry(QtCore.QRect(45, 150, 170, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_theory.setFont(font)
        self.btn_theory.setObjectName("btn_theory")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 220, 80))
        self.label.setMaximumSize(QtCore.QSize(300, 100))
        self.label.setWordWrap(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label.setFont(font)
        self.label.setStyleSheet("white-space: normal;")
        self.label.setObjectName("label")
        MainMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

        # Добавление функционала
        self.btn_create.clicked.connect(lambda: self.open_hasse(MainMenu))
        self.btn_theory.clicked.connect(self.open_theory)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Обучающая программа - Главное меню"))
        self.btn_create.setText(_translate("MainMenu", "Создать диаграмму"))
        self.btn_theory.setText(_translate("MainMenu", "Теория"))
        self.label.setText(_translate("MainMenu", "Обучающая программа визуализации упорядоченных множеств"))

    def open_hasse(self, MainMenu):
        window = MainWindow()
        window.window_closed.connect(lambda: self.open_mainmenu(MainMenu))
        ui = Ui_MainWindow()
        ui.setupUi(window, MainMenu)
        window.show()
        MainMenu.setVisible(False)

    def open_mainmenu(self, MainMenu):
        MainMenu.setVisible(True)

    def open_theory(self):
        global theory
        theory = QtWidgets.QDialog()
        ui = Ui_TheoryDialog()
        ui.setupUi(theory)
        theory.show()