# Form implementation generated from reading ui file 'ui_mainmenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ui_mainwindow import Ui_MainWindow
from ui_theorydialog import Ui_TheoryDialog


class Ui_MainMenu(QtWidgets.QWidget):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(412, 298)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 220, 141, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 180, 141, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 40, 160, 50))
        self.label.setMaximumSize(QtCore.QSize(170, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label.setFont(font)
        self.label.setStyleSheet("white-space: normal;")
        self.label.setObjectName("label")
        MainMenu.setCentralWidget(self.centralwidget)
        self.action_3 = QtGui.QAction(MainMenu)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)


        # Добавление функционала
        self.pushButton.clicked.connect(lambda: self.open_hasse(MainMenu))
        self.pushButton_2.clicked.connect(lambda: self.open_theory(MainMenu))

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Обучающая программа - Главное меню"))
        self.pushButton.setText(_translate("MainMenu", "Создать диаграмму"))
        self.pushButton_2.setText(_translate("MainMenu", "Теория"))
        self.label.setText(_translate("MainMenu", "Обучающая программа визуализации упорядоченных множеств"))

    def open_hasse(self, MainMenu):
        window = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(window, MainMenu)
        window.show()
        MainMenu.close()

    def open_theory(self, MainMenu):
        global theory
        theory = QtWidgets.QDialog()
        ui = Ui_TheoryDialog()
        ui.setupUi(theory)
        theory.show()
