# Form implementation generated from reading ui file 'ui_theorydialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TheoryDialog(object):
    def setupUi(self, TheoryDialog):
        TheoryDialog.setObjectName("TheoryDialog")
        TheoryDialog.resize(660, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TheoryDialog.sizePolicy().hasHeightForWidth())
        TheoryDialog.setSizePolicy(sizePolicy)
        TheoryDialog.setMinimumSize(QtCore.QSize(260, 100))
        TheoryDialog.setMaximumSize(QtCore.QSize(700, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        TheoryDialog.setFont(font)
        TheoryDialog.setStyleSheet("background-color: #FEFFFE;")
        self.gridLayout_2 = QtWidgets.QGridLayout(TheoryDialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(TheoryDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 658, 488))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(10, 10, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setMinimumSize(QtCore.QSize(200, 30))
        self.label_2.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(TheoryDialog)
        QtCore.QMetaObject.connectSlotsByName(TheoryDialog)

    def retranslateUi(self, TheoryDialog):
        _translate = QtCore.QCoreApplication.translate
        TheoryDialog.setWindowTitle(_translate("TheoryDialog", "Теоретические сведения"))
        self.label_2.setText(_translate("TheoryDialog", "<p><strong>Бинарное отношение</strong> &ndash; "
                                                        "отношение между множествами A и B, то есть всякое "
                                                        "подмножество декартова произведения этих множеств.</p>"
                                                        "<p><strong>Отношение порядка</strong> &ndash; бинарное "
                                                        "отношение между элементами данного множества, по своим "
                                                        "свойствам сходное со свойствами отношения неравенства.</p>"
                                                        "<p><strong>Упорядоченное множество</strong> &ndash; множество "
                                                        "вместе с заданным на нем отношением порядка.</p><p><strong>"
                                                        "Диаграмма Хассе</strong> &ndash; это графическое представление"
                                                        " отношения элементов упорядоченного множества.<br />Диаграмма "
                                                        "Хассе предназначена для наглядного графического изображения "
                                                        "отношения порядка, заданного на конечном множестве малой "
                                                        "мощности.</p><p><em>Правила построения:</em></p><ol><li>"
                                                        "Элементы множества изображаются кружками на плоскости;</li>"
                                                        "<li>Если y доминирует над x, то кружок y изображается выше "
                                                        "кружка x, и если есть доминирование, соединяются прямой "
                                                        "линией;</li><li>Если 2 элемента одного уровня доминирования, "
                                                        "они изображаются на одном уровне.</li></ol>"))
        self.label.setText(_translate("TheoryDialog", "Теоретические сведения"))
